# Write Kubernetes Deployment Script
apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-catalog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-catalog
  template:
    metadata:
      labels:
        app: book-catalog
    spec:
      containers: 
      - name: book-catalog
        image: bookimage:1
        ports:
        - containerPort: 8000
        imagePullPolicy: Never
        env:
        - name: DATABASE_URL
          value: "postgresql://varsha1712_user:1acD3a4laqmAbWSC7Pjoi6b8hpBPp8VZ@dpg-crifqabv2p9s738hith0-a.oregon-postgres.render.com/varsha1712"
---
apiVersion: v1
kind: Service
metadata:
  name: book-catalog
spec:
  selector:
    app: book-catalog
  type: NodePort
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30000